### ISSUE TITLE
add a list command

### ISSUE THREAD

**Issue by ilmanzo** [weaveworks/footloose#78] opened 2019-03-06 10:53 UTC
to integrate with external tools, it would be very useful to have a 'list' command that outputs all the machine hostname, and maybe optionally the current host-container port mapping. This can be done with docker but there can be other containers running, we need only the ones created by footloose.

**Comment by dlespiau** [comment] 2019-03-07 10:57
Absolutely! In fact that's captured in issue #7 :) I've added your idea there with more context around this. Just so you know, probably won't have time to do it in the next couple of weeks.

Closing this issue as a duplicate of #7 to keep the the issue list tidy, thanks for the feedback!

**Closed by dlespiau** 2019-03-07 10:57 UTC
